### ISSUE TITLE
Publish to d.org

### ISSUE THREAD

**Issue by davidsheart02** [gioppy/lazyloadxt#1]
Are you planning to publish this to drupal.org?

**Comment by gioppy** [comment]
Hi,
at this time no. I just thinking, but the module needed better coding (I have made in very speed, so some part need to be write better!).

**Comment by davidsheart02** [comment]
Would you be ok with me polishing it up and possibly creating a project for it there?

**Comment by gioppy** [comment]
Sure! Why not!
;)

**Comment by davidsheart02** [comment]
Thanks! If I do that I'll be sure to post a link to it here.

**Comment by gioppy** [comment]
Thanks! If you need an hand for developing or testing ask to me!
;)

**Comment by davidsheart02** [comment]
Sure thing!
